quarkus:
  profile: local
  log:
    sentry:
      ~: ${QUARKUS.LOG.SENTRY.ENABLED}
      dsn: ${QUARKUS.LOG.SENTRY.DSN}
      in-app-packages: com.axuanhogan
      environment: ${API.ENV}
      level: ERROR
    level: INFO
    console:
      format: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{3.}:%L] [%X{REQUEST.ID}] %s%e%n'
  devservices:
    enabled: true
  datasource:
    db-kind: postgresql
    devservices:
      reuse: false
      port: 5433
      db-name: postgres
      username: quarkus
      password: quarkus
  liquibase:
    enabled: true
    migrate-at-start: true
    change-log: db/root.yaml
  hibernate-orm:
    packages:
      - 'com.axuanhogan.common.dao'
    log:
      sql: true
    database:
      generation: validate
  http:
    host: localhost
    access-log:
      enabled: true
    limits:
      max-body-size: 100M
  rest-client:
    connect-timeout: 5000
    read-timeout: 15000
    keycloak-oidc:
      url: ${KEYCLOAK.OIDC.BASE_URI}
      scope: jakarta.inject.Singleton
      read-timeout: 15000
      client-id: ${KEYCLOAK.OIDC.CLIENT_ID}
      client-secret: ${KEYCLOAK.OIDC.CLIENT_SECRET}
mp:
  jwt:
    token:
      header: Cookie
      cookie: ${APPLICATION.AUTH.COOKIE_NAME}
    verify:
      issuer: ${KEYCLOAK.OIDC.ISSUER_URI}
      audiences: ${KEYCLOAK.OIDC.AUDIENCES}
      publickey:
        location: ${KEYCLOAK.OIDC.JWKS_URI}
smallrye:
  jwt:
    always-check-authorization: true
application:
  domain-name: ${APPLICATION.DOMAIN_NAME}
  dao:
    encryption:
      enabled: ${APPLICATION.DAO.ENCRYPTION.ENABLED}
    aes:
      key: ${APPLICATION.DAO.AES.KEY}
      iv: ${APPLICATION.DAO.AES.IV}
